disabled_rules:
  - control_statement
  - identifier_name
  - todo

force_cast: warning
force_try:
  severity: warning
line_length: 130
type_body_length:
  - 300 #warning
  - 400 #error
file_length:
  warning: 500
  error: 1200
